### ISSUE TITLE
Error in CRLI for clustering

### ISSUE THREAD

**Issue by LinglongQian** [WenjieDu/BrewPOTS#17] opened 2024-05-21 14:17 UTC
# the testing stage
crli_results = crli.predict(dataset_for_testing)
crli_prediction = crli_results["clustering"]

--> [2]crli_results = crli.predict(dataset_for_testing)
--> [426]clustering = self.model.kmeans.fit_predict(clustering_latent)
--> [175]raise ValueError(msg_err)

ValueError: Input X contains NaN.
KMeans does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values.

**Comment by WenjieDu** [comment] 2024-05-21 14:18
Hi there 👋,

Thank you so much for your attention to PyPOTS and BrewPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS and BrewPOTS helpful to your work, please star our repositories. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment] 2024-07-16 14:24
I'm closing this issue for now because we cannot reproduce this error. I assume this may be caused by the unstable performance of CRLI.

Reopening this issue is welcome if error reproducing is possible.

**Closed by WenjieDu** 2024-07-16 14:24 UTC
Labels: bug
